### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by gurtajbir** [f1tenth/f1tenth_planning#9]
Hi. I am trying to use this package in conjunction with the F1Tenth gym environment. I cloned the repo and ran `pip install .` which shows that the package was installed. This also appears under `pip3 list` in my virtual environment. However, when I try to run `python3 dynamic_MPC.py` it gives a `ModuleNotFoundError: No module named 'f1tenth_planning'` error. Could you please point me in the right direction?

**Comment by hzheng40** [comment]
This repo is still under development and does not provide any installation. You can refer to the code directly but no support is provided at this moment.
